name: Makefile CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-docker-action@v4

    - name: "get devkitpro pls"
      run: |
        git clone https://github.com/redthing1/dkarm_gba_docker.git
        cd dkarm_gba_docker
        make
        cd ../
    - name: DO IT, JUST DO IT
      run: docker run -it --rm -v $(pwd):/source --user "$(id -u):$(id -g)" dkarm_base:local -l -c "make"
    - name: "send it, cmon"
      uses: actions/upload-artifact@v4
      with:
        name: GBASRB2
        path: GBADoom.gba

