name: Makefile CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: "get devkitpro pls"
      run: |
        wget https://apt.devkitpro.org/install-devkitpro-pacman
        chmod +x ./install-devkitpro-pacman
        sudo ./install-devkitpro-pacman
        exit
        sudo dkp-pacman --noconfirm -S gba-dev
    - name: DO IT, JUST DO IT
      run: |
        export DEVKITPRO=/opt/devkitpro
        export DEVKITARM=/opt/devkitpro/devkitARM
        make
    - name: "send it, cmon"
      uses: actions/upload-artifact@v4
      with:
        name: GBASRB2
        path: GBADoom.gba

