name: Makefile CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-docker-action@v4

    - name: "get devkitarm pls"
      run: | # does this do the job?
        docker image pull devkitpro/devkitarm
    - name: DO IT, JUST DO IT
      run: docker run -i --rm -v $(pwd):/${GITHUB_WORKSPACE} --user "$(id -u):$(id -g)" devkitpro/devkitarm:latest -l -c "make"
    - name: "send it, cmon"
      uses: actions/upload-artifact@v4
      with:
        name: GBASRB2
        path: GBADoom.gba

